[package]
name = "epicsitegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.1"
pathdiff = "0.2.1"
pest = "2.7.9"
pest_derive = "2.7.9"
yaml-rust2 = "0.8.0"
